version: '3.5'

services:
  crdb:
    image: cockroachdb/cockroach:v20.2.10
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_USER=admin
      - COCKROACH_PASSWORD=amdin

volumes:
  cockroach-data: